# Generated by Django 6.0.6 on 2026-06-24 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(choices=[('stock_in', 'entrada'), ('stock_out', 'salida')], default='stock_out', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.CharField(default='venta', max_length=50)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product')),
            ],
        ),
    ]
