upstream auth_service {
    server auth_service:8001;
}

upstream inventory_service {
    server inventory_service:8002;
}

upstream sales_service {
    server sales_service:8003;
}

server {
    listen 80;

    location /api/auth/ {
        proxy_pass http://auth_service/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/inventory/ {
        proxy_pass http://inventory_service/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/sales/ {
        proxy_pass http://sales_service/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}