version: '3.9'

services:

  auth_db:
    image: postgres:16

    container_name: auth_db

    restart: always

    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - auth_postgres_data:/var/lib/postgresql/data


  inventory_db:
    image: postgres:16
    container_name: inventory_db
    
    restart: always

    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports: 
        - "5433:5432"

    volumes:
       - inventory_postgres_data:/var/lib/postgresql/data

  sales_db:
    image: postgres:16

    container_name: sales_db
    
    restart: always

    environment:
      POSTGRES_DB: sales_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports: 
      - "5434:5432"

    volumes:
      - sales_postgres_data:/var/lib/postgresql/data
    
  auth_service:
    build:
      context: ./services/auth_service

    container_name: auth_service

    command: python manage.py runserver 0.0.0.0:8001

    volumes:
      - ./services/auth_service:/app

    ports:
      - "8001:8001"

    environment:
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}

    depends_on:
      - auth_db


  inventory_service:
    build:
      context: ./services/inventory_service

    container_name: inventory_service

    command: python manage.py runserver 0.0.0.0:8002

    volumes:
      - ./services/inventory_service:/app

    ports:
      - "8002:8002"

    environment:
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}

    depends_on:
      - inventory_db

    networks:
      default:
        aliases:
          - inventory-service

  sales_service:
    build:
      context: ./services/sales_service

    container_name: sales_service
    command: python manage.py runserver 0.0.0.0:8003

    volumes:
      - ./services/sales_service:/app

    ports:
      - "8003:8003"

    environment:
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}

    depends_on:
      - sales_db
      - inventory_service

  api_gateway:
    image: nginx:alpine

    container_name: api_gateway

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - auth_service
      - inventory_service
      - sales_service

volumes:
  auth_postgres_data:
  inventory_postgres_data:
  sales_postgres_data: